### ISSUE TITLE
Add UMAP visualization to QC report

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpcaTools#121]
**Is your feature request related to a problem? Please describe.**

People like to see UMAPs of the data, so we should provide them if we can!

**Describe the solution you'd like**

If there is a UMAP matrix in the provided SCE object, we should show it in the report somewhere (probably near the top). If we wanted to, we could fall back to tSNE or PCA if those are present. 

**Describe alternatives you've considered**
We could calculate the UMAP within the notebook if it is missing, but I think it may make sense to make this more of an optional thing, and only show it if the UMAP was previously calculated and will be present in the download. 

**Additional context**

Some of the implementation may depend on the implementation of https://github.com/alexslemonade/scpca-nf/issues/203; if we can not include a soft filter such that only some cells are included in the UMAP visualization, we may need to pass in a 3rd object which is a further filtered version of the object (with damaged or low-information cells removed) from which to plot the UMAP.

We may also want to add some more summary lines to the report that describe the number of cells that were removed by miQC filtering and/or low information content (few genes).

**Comment by jaclyn-taroni** [comment]
Close #20? (This is more detailed!)

**Comment by jashapiro** [comment]
Reopening since the latest version of scpcaTools no longer builds due to a lost dependency. Closing this issue will require us to fix #134

**Comment by allyhawkins** [comment]
Can this be closed again since #134 is closed?

**Comment by jashapiro** [comment]
Yes!
