### ISSUE TITLE
Add cell clustering to QC report

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpcaTools#122]
**Is your feature request related to a problem? Please describe.**

Once we start to have visualization with #121 , we will probably want to add some color to the plot, which probably means adding clustering to the visualization.

**Describe the solution you'd like**

Clustering should be added separately, likely as part of the core scpca-nf workflow, but the notebooks should notice if there is clustering present and use it to color the UMAP visualization.

**Describe alternatives you've considered**

We could do clustering internal to the notebook, but we probably don't want to.

**Additional context**

This was originally part of #20. I am separating it out here, since we have a separate issue for UMAP alone.

**Comment by allyhawkins** [comment]
Closing this because we decided we don't want to add clustering right now.
