### ISSUE TITLE
Function for combining SingleCellExperiment objects

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpcaTools#146]
Before being able to do integration, we will need to be able to merge SCE objects into one object to obtain combined highly variable genes and calculate PCA. Additionally, the input for the integration methods we plan to support use a merged SCE object. 

This function should take as input a list of individual SCE objects, all already containing normalized data. Inside the function we will need to match up all of the `colData`, filling in any data that is only found in part of the libraries being integrated with `NA`. We will also want to subset to only shared genes. The new columns of this merged object should be named with the cell barcode and the library ID as barcodes could be overlapping between libraries. 

The output should be the merged object with a new column in the `colData` corresponding to the library ID for each cell.

**Comment by sjspielman** [comment]
A couple quick discussion items for this, specifically in how it might differ from our original implementation:

- Originally, we check if column names match among SCEs and we add a "dummy" column with all `NA` values if any columns are missing to ensure a full match. I would tend to prefer _not_ to do this here but just error out fully if all colData names don't match.
- Originally we removed any altExps before merging SCEs. I think we need to _keep_ altExps here (with associated book-keeping to always link back to originating data), or at least have an argument for whether the altExps should be preserved.
- Originally we allow for a vector of rowData column names which should not be altered, and I think we should still do this (keeping default `NULL`).
- Originally we removed any colData columns _other than_ batch, percellQC columns, and mitochondria columns. I'm on the fence for whether we want to keep this?

**Comment by allyhawkins** [comment]
> * Originally, we check if column names match among SCEs and we add a "dummy" column with all `NA` values if any columns are missing to ensure a full match. I would tend to prefer _not_ to do this here but just error out fully if all colData names don't match.

I think you could have an option to require matching colData or not. With data from `scpca-nf` we would expect them to fully match, but if someone is using this package for their own data then who knows what type of colData is in each object and I don't think it's necessarily required that all colData be present for all datasets. 

Maybe instead of requiring matching colData, we have an option to input columns to preserve. All other columns would be removed. 

> * Originally we removed any altExps before merging SCEs. I think we need to _keep_ altExps here (with associated book-keeping to always link back to originating data), or at least have an argument for whether the altExps should be preserved.

Yes to the argument... I think generally we probably want to keep them. 

> * Originally we allow for a vector of rowData column names which should not be altered, and I think we should still do this (keeping default `NULL`).

Yes agreed on this. 

> * Originally we removed any colData columns _other than_ batch, percellQC columns, and mitochondria columns. I'm on the fence for whether we want to keep this?

See my comment above on including an argument for column data to preserve. But generally I don't think we should remove all but these columns. That was specific to removing all the extra data calculated by HCA. I think we should have an argument of columns to preserve and the default would be the columns that are output by `scpca-nf` (so per cell QC, miQC, and batch/libraryID).
