### ISSUE TITLE
Add processing information to QC report 

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpcaTools#17]
As part of the QC report, we should include information about processing including software information and versions. This may involve modifying the scpcaTools read functions and attaching this information to the SCE metadata and then grabbing it from the SCE to output during the report.

**Comment by jashapiro** [comment]
With the current version of `salmon` (1.5.1) some of the expected files are not being produced (see https://github.com/COMBINE-lab/salmon/issues/688), which may limit our ability to use the processor file output for tracking this information. We will likely want to have some additional way of tracking the command invocation for steps of our workflow with the output files. This may involve additions to https://github.com/AlexsLemonade/scpca-nf, but we should decide here what fields we would like to include. 

We should make this flexible so missing information does not result in failure. 

Some initial thoughts:
-`pipeline`: probably a reference to https://github.com/AlexsLemonade/scpca-nf most of the time, with either a release tag or commit id
- `reference` Ensembl 103, etc.
- `index`
- `filter` (emptydrops etc.)

What else would people want to see?
