### ISSUE TITLE
Add function to calculate batch ARI

### ISSUE THREAD

**Issue by cbethell** [AlexsLemonade/scpcaTools#175]
**Is your feature request related to a problem? Please describe.**
Per https://github.com/AlexsLemonade/scpca-downstream-analyses/issues/352#issuecomment-1593053590:
We are finding that we may have more than one use case for the integration performance metrics used in the `sc-data-integration` repo. That said, we should get these functions in a single place so that they can be utilized across multiple repos post-integration.

**Describe the solution you'd like**
Add a function for calculating `batch ARI` similar to the script in the `sc-data-integration` repo: https://github.com/AlexsLemonade/sc-data-integration/blob/main/scripts/utils/calculate-ARI.R

**Comment by allyhawkins** [comment]
@sjspielman and @jashapiro could you please leave any additional thoughts or comments by EOD on Wednesday 6/28? Thank you!

**Comment by cbethell** [comment]
Addressed by #176
