### ISSUE TITLE
Attach basic statistics of per cell QC metrics in QC report

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpcaTools#18]
In the QC report we should calculate some metrics on a per cell level. This can be done using `scpcaTools::add_cell_mito_qc()`, which will add `colData` to the SCE. We will need to extract that `colData` and output information like: 

- UMI/cell
- Genes/cell
- % mito/cell 

In doing this, we should think about including both a table with the median and mean value of these numbers (and maybe standard dev?) and a plot showing the distribution of these values.

**Comment by jashapiro** [comment]
In the table here, we should include the number of cells post-emptyDrops Filtering as well.
