### ISSUE TITLE
Add knee plot to QC report

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpcaTools#19]
We may want to include a knee plot in the QC report for each sample where we highlight cells that are included and excluded. This will require us to have information about both the unfiltered and filtered cells which could be read in as two separate SCE's, or we could use the unfiltered sce and highlight just the cell barcodes that have passed filtering.

**Comment by jashapiro** [comment]
A version of this was added in https://github.com/AlexsLemonade/scpcaTools/pull/45, though the current knee plot does not have a log scale on the "rank" axis, which needs to be fixed. The PR to fix that could probably also use a graphical review, which I don't think it got before.
