### ISSUE TITLE
Add tests for `processing_pcs.R` functions

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpcaTools#196]
We have a couple helper functions in https://github.com/AlexsLemonade/scpcaTools/blob/62ef2e9ab3893a5f1a1cd0e5f2ec4a53a0753cad/R/processing_pcs.R that are currently untested. This issue tracks adding (small!) unit tests for those functions - `filter_pcs()` and `downsample_pcs()`.

**Comment by allyhawkins** [comment]
I already wrote those - https://github.com/AlexsLemonade/scpcaTools/blob/62ef2e9ab3893a5f1a1cd0e5f2ec4a53a0753cad/tests/testthat/test-integration_metrics.R#L22 and https://github.com/AlexsLemonade/scpcaTools/blob/62ef2e9ab3893a5f1a1cd0e5f2ec4a53a0753cad/tests/testthat/test-integration_metrics.R#L42

**Comment by sjspielman** [comment]
Ah! I looked for a file `test-processing_pcs.R` and since it wasn't there I assumed there were no tests, but I was super wrong! I'll just go ahead and update the `filter_pcs()` test as part of #198 (except pending discussion, since I might not need to given what I wrote in the PR!).
