### ISSUE TITLE
Update CONTRIBUTING with preferred R package repo

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpcaTools#227]
We might want to indicate in `CONTRIBUTING` that we prefer defaulting to `CRAN` (or do we want to shake things up?) for package repositories. In theory this should happen automatically because we have these repos set (see below), but apparently sometimes it does not happen for reasons I don't quite understand so we might want to make an explicit note of it.

https://github.com/AlexsLemonade/scpcaTools/blob/139a001cd590dc85df25db39597cd3d26c48c047/docker/renv.lock#L1-L30

**Comment by jashapiro** [comment]
I am closing this, because I think we actually don't want this default anymore.
