### ISSUE TITLE
Fix merging metadata bug

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpcaTools#250]
I'm pretty sure we have a bug in how we handle merging SCE metadata, such that we may have accidentally ended up with a lot of duplicate items. I have not dug into this much, but noticed that something looked funky. 

This issue therefore encompasses formally diagnosing the bug, and then fixing it.

**Comment by allyhawkins** [comment]
What do you mean we have a lot of duplicate items?

**Comment by sjspielman** [comment]
> What do you mean we have a lot of duplicate items?

I thought I was seeing too many `library_id` and/or `sample_id` fields that weren't properly nested inside the libraries from whence they came. But, I am jumping around quite a bit so I didn't really dig it, and I am also not 100% convinced I didn't just misread some output! So, this issue is for me to figure out whether I saw a real thing or not later... 🙃
