### ISSUE TITLE
Ensure cell type labels are retained when merging SCEs

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpcaTools#258]
When merging SCEs in `scpcaTools::merge_sce_list()`, we use a vector of colData columns to retain. Missing from this list are cell type annotation columns, but we would definitely like to retain them. We'll need to update the function, and its docs, accordingly.

**Comment by allyhawkins** [comment]
My understanding from DSTM was that we don't want to actually change the function, we just want to change the vector of column names that we provide when calling the function in `scpca-nf`. We will need to add the `retain_coldata_cols` argument here: 
https://github.com/AlexsLemonade/scpca-nf/blob/f08ce452f95f88e169217c114aef1c1321a3688c/bin/merge_sces.R#L132

**Comment by sjspielman** [comment]
Indeed, this will happen in `scpca-nf`.
