### ISSUE TITLE
Add function(s) for reading and adding CITE-seq/cellhash data to a SCE

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpcaTools#28]
CITE-seq and cell hash data can be integrated into a SingeCellExperiment as an [Alternative Experiment](https://rdrr.io/bioc/SingleCellExperiment/man/altExps.html), so we need functions to do this. 

This should be doable partly with existing functions like `read_alevin_mtx()` to get the count data from alevin-fry output.

The next step is to add the alternative experiment matrix, but first we will need figure out best practice for cells that are found in one data set but not the other. In preliminary investigations, we find cells that are found only in the RNA-seq data, as well as only in the CITE-seq data. (I initially thought there might be some cell barcode mapping that needs to happen, but that doesn't seem to be the case, at least not for the initial test data.) 

The simplest solution is to simply reduce the output SCE to only those cells found in **both** data types, but we could also add NAs to the CITE-seq data for any cells found in RNA-seq but not in CITE-seq. I don't think there is any point in keeping cells found in CITE-seq but not found in the RNA-seq data, but I could be convinced otherwise.

**Comment by jaclyn-taroni** [comment]
Tagging myself (@jaclyn-taroni) and @allyhawkins for input. Question from Ally (paraphrasing): What is the frequency of non-overlapping cells?

**Comment by jashapiro** [comment]
Some quick stats from the one example I have looked at:

CITE-seq cells (no filter): 80,094 
RNA cells (filtered with emptyDrops): 7,051
RNA cells with a corresponding CITE-seq cell: 6,884 (97.6%)
RNA cells with no CITE-seq data: 167

This is the distribution of counts in the missing cells: 
![image](https://user-images.githubusercontent.com/20483/127906732-c1b7709a-c481-445d-86fd-157adf078fd2.png)
Not all are very low expression cells, but the vast majority are.

As I wrote that, I realized that I should compare to the present cells, so here is that:
![image](https://user-images.githubusercontent.com/20483/127908005-c5174bca-ae7d-4ee8-9900-dd25f723993c.png)

So I am a lot less worried about the missing data! 

Still, at least a couple cells might still pass even a stricter QC filter for RNA-seq. Do we want to purge the cells with no CITE-seq data or keep them?

**Comment by allyhawkins** [comment]
I am definitely in agreement about throwing out cells that appear in CITE but don't appear in RNA. Those don't seem like they would contain valid information. 

As far as keeping cells that don't have CITE but do have RNA, I would think we want to keep those (although it does appear that in the filtered matrix they would mostly be removed). I can imagine scenarios where CITE-seq is not 100% efficient so I think we would still want to keep the RNA information.

**Comment by jashapiro** [comment]
After the meeting this afternoon, I was realizing that we will almost certainly want to keep the RNA-seq data even if there is no CITE-seq, especially for the unfiltered data set!

**Comment by jashapiro** [comment]
Just for reference, the opposite comparison: CITEseq count distributions for cells with and without (filtered) RNAseq data.
![image](https://user-images.githubusercontent.com/20483/127917981-9a84f834-0ef8-4e49-8c7f-07aa05ffce79.png)

**Comment by jaclyn-taroni** [comment]
I do not have anything else to add post-these plots!
