### ISSUE TITLE
Filtered RDS: Remove zero count genes

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/scpcaTools#36]
We have talked about an approach where we perform minimal filtering ourselves but provide relevant metadata in the filtered RDS object to facilitate filtering by the user (and perhaps make some suggestions https://github.com/AlexsLemonade/alsf-scpca/issues/134 about how we'd filter it!).

The minimal filtering on the gene level we talked about was **removing genes that are not detected at all**. This issue is to track that work. I have a _guess_ about where this would be performed, but it is not a very educated one so I'll leave it here for now.

**Comment by jashapiro** [comment]
I had second thoughts about whether we want to actually implement this, which I described here: https://github.com/AlexsLemonade/scpca-nf/pull/35#issuecomment-925428083
