### ISSUE TITLE
Add function to generate QC report

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpcaTools#7]
Along the same lines as https://github.com/AlexsLemonade/alsf-scpca/issues/43, we should add in a function here to generate the QC report. Exactly what tools will be used to generate QC metrics still need to be figured out (ie. are we going to use miQC or not). Writing this down now since this is something we have talked about and I think would be useful to integrate with the current `import_quant_data` functions so we can get a QC report (and maybe even a dataframe with metrics?) for each sample.

**Comment by jashapiro** [comment]
I am working on a basic version of this now, which will do the basic part of being a function that turns a template notebook into an html qc report with a SingleCellExperiment (and other info?) as input. After that is done, we will want to think about what components should go into the report. 

Thoughts at this point (partially inspired by AlevinQC & CR's `web_output.html`):
- Processing info 
  - Software, versions, etc.
  - can we attach this to SCE's as metadata? If so, we might well want to make that part of scpcaTools read functions, etc.
- Number of cells
- UMIs per cell stats (mean, median, sd?)
- Genes per cell
- Genes detected
- Knee plot with included/excluded cell highlighted (this might mean require 2 sce inputs: filtered & unfiltered, or at least unfiltered + the filtered cell list)
- Distribution of mito %
- Scatter plot of cells with UMI & expressed genes like we use in training?
- Maybe a UMAP plot & clusters (filtered cells only)?

Most of these parts can be broken out into separate issues, if we agree that they should be included. @jaclyn-taroni suggested that many of the plots might be made interactive. I am not opposed to that idea, but we will have to pick which interactive tool we use! I just learned about [`plotly::ggplotly()`](https://plotly.com/ggplot2/), which might make this easy (and easy to add later if we decide not to use it for initial versions!).

**Comment by allyhawkins** [comment]
I think all of this looks good in terms of what to include. For the stats for UMI/cell and genes per cell, I like the idea of  making both a table and a plot for this. The scatter plot we make in training could be sufficient, but it also could be helpful to show a trio of plots with the distribution of UMI/cell, genes/cell, and mito content post filtering. I think it will depend on which one looks better visually. 

My only concern with the knee plot is for the single-nuclei samples. We know that they don't perform well with the knee filtering so I'm not sure how this would look and do we want to include this if we aren't using a knee plot for filtering?
