### ISSUE TITLE
Add function to read spatial transcriptomics quantification output into R as SpatialExperiment

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpcaTools#75]
Following quantification of the spatial transcriptomics libraries with Spaceranger (+/- Alevin-fry) we will need to read in that output data into R as a SpatialExperiment. Especially with the error that is currently in the `SpatialExperiment::read10XVisium` function, we should create our own function that follows the steps on the [SpatialExperiment vignette.](https://bioconductor.org/packages/release/bioc/vignettes/SpatialExperiment/inst/doc/SpatialExperiment.html#22_Spot-based) 
We can use the [`create_spaceranger_spe`](https://github.com/AlexsLemonade/alsf-scpca/blob/9d5840fa9c80e6969b16d03d5b000e6a6b19fcfe/analysis/benchmarking-functions/R/create_spaceranger_spe.R) or [`create_fry_spaceranger_spe`](https://github.com/AlexsLemonade/alsf-scpca/blob/allyhawkins/spatial-transcriptomics-benchmarking-2/analysis/benchmarking-functions/R/create_fry_spaceranger_spe.R) functions that I used during benchmarking as a guide. 

The first step would be to create the function that can read in the Spaceranger output and then if we are going to use Alevin-fry we can later modify the function to only create the SpatialExperiment from spots that are found in both Alevin-fry and Spaceranger (following the [Alevin-fry tutorial](https://combine-lab.github.io/alevin-fry-tutorials/2021/af-spatial/)).

**Comment by jashapiro** [comment]
Just noting that read10xVisium has been corrected by https://github.com/drighelli/SpatialExperiment/pull/91.
If this results in a bugfix update to`SpatialExperiment` soon, we may be able to use it. But we can also change to rely on it later.

**Comment by allyhawkins** [comment]
As we have currently decided to use Spaceranger and provide the output files from Spaceranger, we will not need to add in this function right now.
