### ISSUE TITLE
Proposal: round count matrices on import (optionally)

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpcaTools#85]
**Is your feature request related to a problem? Please describe.**
I ran into trouble with Seurat when using an internal function that expected an integer count matrix. With the `crlike_em` quantification of alevin-fry, this assumption was not met. I imagine that there are other places where this issue could occur, and a downstream user might be stumped for a while (as I was!).

**Describe the solution you'd like**
At import, we can round count matrices to integer values. This could happen by default, but with an option to turn rounding off. 

We will also need to update [scpca-docs](https://github.com/AlexsLemonade/scpca-docs) to say that we are using rounded EM results if we make this change.

**Describe alternatives you've considered**
Leaving things as they are... This would require more documentation, and maybe even a warning when non-integer counts were read in.

**Additional context**
There is a potential small loss of precision here, but at the scale & noisiness of single-cell experiments, I don't expect it to be large.

At the other end, an integer matrix is potentially smaller to store (less so with sparse matrices), so there can be some savings here.

**Comment by jashapiro** [comment]
Tagging @allyhawkins @jaclyn-taroni for comment. If we are going to do this, we should probably do it before the next set of samples are processed.

**Comment by jaclyn-taroni** [comment]
I will preface this with this opinion is not super strongly held and that I assume, based on the above, that the Seurat warning or error is uninformative.

To me, it seems like removing a potential point of friction for downstream users outweighs the downsides for us which I understand to be: 1. a docs update 2. a loss of precision that I also am not particularly concerned about.

Plus we can rerun things without redoing the mapping now 🤩
