### ISSUE TITLE
Handle errors for emptyDropsCellRanger

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpcaTools#90]
**Is your feature request related to a problem? Please describe.**
When processing the Green project again, there was a failure in the new filtering strategy of using `emptyDropsCellRanger` that was causing the entire run to fail. 
<img width="543" alt="Screen Shot 2022-02-08 at 2 30 50 PM" src="https://user-images.githubusercontent.com/54039191/153070521-a1d48778-d69b-4693-9076-936a57c3abff.png">
 
When looking at the previous QC report for this sample, it has really low cell counts and also failed miQC so this isn't surprising. I thought we should figure out a way to handle these errors and was back and forth on if we should just not filter at all or if we should filter using `emptyDrops`, as that is much less likely to be unable to find an ambient profile or throw an error like this so wanted to see if anyone else had opinions or thoughts before finishing up the changes to the function. 

**Describe the solution you'd like**
We could just not perform filtering in this event and return the unfiltered sce. The question with this is then do we just remove the filtered file altogether (this seems hard and not necessary for just a few samples)? Or do we add a warning for that sample in the QC report and/or metadata that the filtered file is the same as the unfiltered file. I think I'm favoring this approach because if a sample is this poor quality, are we confident in being able to filter it and this seems the most straight forward to explain if we add a warning in the QC report if the unfiltered SCE and filtered SCE are equivalent. 

**Describe alternatives you've considered**
In testing, using `emptyDrops` is able to identify an ambient profile when `emptyDropsCellRanger` cannot, so we could use `emptyDrops` in the event of failures. We can then add a field to the metadata that has the type of `emptyDrops` filtering that was performed. The downfall of this would be explaining in the docs why there are two different methods, which I don't think is completely straight forward... 

**Additional context**
Tagging @jashapiro and @jaclyn-taroni for any thoughts on this.

**Comment by jashapiro** [comment]
I agree we don't want to not have an unfiltered file, but I don't think we should make the filtered file the same as unfiltered in the event of failure. 

EmptyDropsCellRanger assumes a certain minimum number of droplets (defined by `ind.min` and 45000 by default) with > 0 expression, so my guess is that this sample is falling below that threshold. We could try to get fancy and try to adjust the `ind.min` parameter in the event of failure to get to a set of ambient cells in the event of failure, but I don't know how successful we might expect that to be. I have ideas, but it could be a rabbit hole

I was also thinking about something in between: if EmptyDropsCellRanger fails, can we use a hard filter? i.e., could we keep the top 1000 droplets, or those with total counts over 100? The advantage of an approach like this is it will be much simpler to explain.

Either way, I think we _definitely_ want to have something about failing filtering both in the QC report and the metadata (so we have the option to display that in the portal). I would suggest we should do a minimal version of this now with some kind of hard filter, and then maybe circle back to improving the filtering of bad samples in the future?

**Comment by jaclyn-taroni** [comment]
> I was also thinking about something in between: if EmptyDropsCellRanger fails, can we use a hard filter? i.e., could we keep the top 1000 droplets, or those with total counts over 100? The advantage of an approach like this is it will be much simpler to explain.
> 
> Either way, I think we _definitely_ want to have something about failing filtering both in the QC report and the metadata (so we have the option to display that in the portal). I would suggest we should do a minimal version of this now with some kind of hard filter, and then maybe circle back to improving the filtering of bad samples in the future?

+1
